"use client"

import { useState } from "react"
import { AppShell } from "@/components/layout/app-shell"
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card"
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"
import { reports, interviewHistory, userStats } from "@/lib/mock-data"
import {
  Download,
  FileText,
  Video,
  FileBarChart,
  Calendar,
  Search,
  TrendingUp,
  Eye,
  Trash2,
} from "lucide-react"
import { cn } from "@/lib/utils"
import { motion } from "framer-motion"
import { staggerContainer, staggerItem, cardVariants, viewportOnce } from "@/lib/animations"

type ReportType = "all" | "interview" | "resume" | "weekly"

const reportTypeIcons = {
  interview: Video,
  resume: FileText,
  weekly: FileBarChart,
}

const reportTypeColors = {
  interview: "bg-blue-500/10 text-blue-500",
  resume: "bg-green-500/10 text-green-500",
  weekly: "bg-purple-500/10 text-purple-500",
}

export default function ReportsPage() {
  const [reportsList, setReportsList]     = useState(reports)
  const [search, setSearch]               = useState("")
  const [activeFilter, setActiveFilter]   = useState<ReportType>("all")
  const [selectedReport, setSelectedReport] = useState<string | null>(null)
  const [deleteConfirmId, setDeleteConfirmId] = useState<string | null>(null)

  const filters: { id: ReportType; label: string }[] = [
    { id: "all", label: "All Reports" },
    { id: "interview", label: "Interview" },
    { id: "resume", label: "Resume" },
    { id: "weekly", label: "Weekly" },
  ]

  function handleDeleteReport(id: string) {
    setReportsList(prev => prev.filter(r => r.id !== id))
    if (selectedReport === id) setSelectedReport(null)
    setDeleteConfirmId(null)
  }

  const filteredReports = reportsList.filter(report => {
    const matchesSearch = report.title.toLowerCase().includes(search.toLowerCase()) ||
      report.subtitle.toLowerCase().includes(search.toLowerCase())
    
    if (!matchesSearch) return false
    if (activeFilter === "all") return true
    return report.type === activeFilter
  })

  const handleDownload = (report: typeof reports[0]) => {
    // Generate mock report content based on type
    let content = ""
    
    if (report.type === "interview") {
      const interview = interviewHistory.find(i => report.title.includes(i.category))
      content = `
INTERMATE INTERVIEW REPORT
==========================
${report.title}
${report.subtitle}
Date: ${report.date}
Score: ${report.score}%

${interview ? `
DETAILS:
- Duration: ${interview.duration} minutes
- Questions: ${interview.questions}
- Category: ${interview.category}

STRENGTHS:
${interview.strengths.map(s => `- ${s}`).join("\n")}

AREAS FOR IMPROVEMENT:
${interview.improvements.map(i => `- ${i}`).join("\n")}
` : ""}

Generated by InterMate - AI-Powered Interview Preparation Platform
      `
    } else if (report.type === "resume") {
      content = `
INTERMATE RESUME ANALYSIS REPORT
================================
${report.title}
${report.subtitle}
Date: ${report.date}
ATS Score: ${report.score}%

This resume has been analyzed for ATS compatibility and keyword optimization.
Please refer to the full analysis in the application for detailed suggestions.

Generated by InterMate - AI-Powered Resume Analyzer
      `
    } else {
      content = `
INTERMATE WEEKLY PROGRESS REPORT
================================
${report.title}
${report.subtitle}
Date: ${report.date}

WEEKLY SUMMARY:
- Total Interviews: ${userStats.totalInterviews}
- Average Score: ${userStats.averageScore}%
- Practice Hours: ${userStats.practiceHours}
- Badges Earned: ${userStats.badgesEarned}

SKILL PROGRESS:
${userStats.skillProgress.map(s => `- ${s.skill}: ${s.score}% (${s.trend})`).join("\n")}

Generated by InterMate - Your Career Preparation Companion
      `
    }

    const blob = new Blob([content], { type: "text/plain" })
    const url = URL.createObjectURL(blob)
    const a = document.createElement("a")
    a.href = url
    a.download = `InterMate_${report.type}_Report_${report.date}.txt`
    document.body.appendChild(a)
    a.click()
    document.body.removeChild(a)
    URL.revokeObjectURL(url)
  }

  const getScoreColor = (score: number | null) => {
    if (!score) return "text-muted-foreground"
    if (score >= 85) return "text-green-500"
    if (score >= 70) return "text-primary"
    if (score >= 50) return "text-yellow-500"
    return "text-red-500"
  }

  const selectedReportData = reports.find(r => r.id === selectedReport)

  return (
    <AppShell 
      title="Reports"
      description="View and download your interview and resume reports"
    >
      <motion.div
        className="space-y-6"
        initial="hidden"
        animate="visible"
        variants={staggerContainer}
      >
        {/* Stats */}
        <motion.div variants={staggerItem} className="grid gap-4 md:grid-cols-4">
          <Card>
            <CardContent className="flex items-center gap-4 p-4">
              <div className="flex h-12 w-12 items-center justify-center rounded-lg bg-primary/10">
                <FileBarChart className="h-6 w-6 text-primary" />
              </div>
              <div>
                <p className="text-2xl font-bold">{reportsList.length}</p>
                <p className="text-sm text-muted-foreground">Total Reports</p>
              </div>
            </CardContent>
          </Card>
          <Card>
            <CardContent className="flex items-center gap-4 p-4">
              <div className="flex h-12 w-12 items-center justify-center rounded-lg bg-blue-500/10">
                <Video className="h-6 w-6 text-blue-500" />
              </div>
              <div>
                <p className="text-2xl font-bold">
                  {reportsList.filter(r => r.type === "interview").length}
                </p>
                <p className="text-sm text-muted-foreground">Interview Reports</p>
              </div>
            </CardContent>
          </Card>
          <Card>
            <CardContent className="flex items-center gap-4 p-4">
              <div className="flex h-12 w-12 items-center justify-center rounded-lg bg-green-500/10">
                <FileText className="h-6 w-6 text-green-500" />
              </div>
              <div>
                <p className="text-2xl font-bold">
                  {reportsList.filter(r => r.type === "resume").length}
                </p>
                <p className="text-sm text-muted-foreground">Resume Reports</p>
              </div>
            </CardContent>
          </Card>
          <Card>
            <CardContent className="flex items-center gap-4 p-4">
              <div className="flex h-12 w-12 items-center justify-center rounded-lg bg-yellow-500/10">
                <TrendingUp className="h-6 w-6 text-yellow-500" />
              </div>
              <div>
                <p className="text-2xl font-bold">{userStats.averageScore}%</p>
                <p className="text-sm text-muted-foreground">Avg. Score</p>
              </div>
            </CardContent>
          </Card>
        </motion.div>

        {/* Search and Filters */}
        <div className="flex flex-col gap-4 md:flex-row md:items-center md:justify-between">
          <div className="relative flex-1 max-w-md">
            <Search className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-muted-foreground" />
            <Input
              placeholder="Search reports..."
              value={search}
              onChange={(e) => setSearch(e.target.value)}
              className="pl-9"
            />
          </div>
          <div className="flex gap-2">
            {filters.map((filter) => (
              <Button
                key={filter.id}
                variant={activeFilter === filter.id ? "default" : "outline"}
                size="sm"
                onClick={() => setActiveFilter(filter.id)}
              >
                {filter.label}
              </Button>
            ))}
          </div>
        </div>

        <motion.div variants={staggerItem} className="grid gap-6 lg:grid-cols-3">
          {/* Reports List */}
          <div className="lg:col-span-2 space-y-3">
            {filteredReports.map((report) => {
              const Icon = reportTypeIcons[report.type as keyof typeof reportTypeIcons] || FileText
              const colors = reportTypeColors[report.type as keyof typeof reportTypeColors] || "bg-muted text-muted-foreground"
              
              return (
                <Card 
                  key={report.id}
                  className={cn(
                    "cursor-pointer transition-all hover:border-primary/50",
                    selectedReport === report.id && "border-primary"
                  )}
                  onClick={() => setSelectedReport(report.id)}
                >
                  <CardContent className="p-4">
                    <div className="flex items-center gap-4">
                      <div className={cn(
                        "flex h-12 w-12 shrink-0 items-center justify-center rounded-lg",
                        colors
                      )}>
                        <Icon className="h-6 w-6" />
                      </div>
                      <div className="flex-1 min-w-0">
                        <div className="flex items-center justify-between">
                          <p className="font-medium truncate">{report.title}</p>
                          {report.score && (
                            <span className={cn("font-bold", getScoreColor(report.score))}>
                              {report.score}%
                            </span>
                          )}
                        </div>
                        <p className="text-sm text-muted-foreground truncate">
                          {report.subtitle}
                        </p>
                        <div className="flex items-center gap-4 mt-2 text-xs text-muted-foreground">
                          <span className="flex items-center gap-1">
                            <Calendar className="h-3 w-3" />
                            {report.date}
                          </span>
                          <span className="capitalize">{report.type} Report</span>
                        </div>
                      </div>
                      <div className="flex items-center gap-1" onClick={e => e.stopPropagation()}>
                        <Button
                          variant="ghost"
                          size="icon"
                          onClick={() => handleDownload(report)}
                        >
                          <Download className="h-4 w-4" />
                        </Button>
                        {deleteConfirmId === report.id ? (
                          <span className="flex items-center gap-1">
                            <Button
                              size="sm" variant="destructive"
                              className="h-7 px-2 text-xs"
                              onClick={() => handleDeleteReport(report.id)}
                            >
                              Delete
                            </Button>
                            <Button
                              size="sm" variant="ghost"
                              className="h-7 px-2 text-xs"
                              onClick={() => setDeleteConfirmId(null)}
                            >
                              Cancel
                            </Button>
                          </span>
                        ) : (
                          <Button
                            variant="ghost" size="icon"
                            className="text-muted-foreground hover:text-red-500"
                            onClick={() => setDeleteConfirmId(report.id)}
                          >
                            <Trash2 className="h-4 w-4" />
                          </Button>
                        )}
                      </div>
                    </div>
                  </CardContent>
                </Card>
              )
            })}

            {filteredReports.length === 0 && (
              <div className="text-center py-12">
                <FileBarChart className="mx-auto h-12 w-12 text-muted-foreground" />
                <h3 className="mt-4 text-lg font-medium">No reports found</h3>
                <p className="text-muted-foreground">Try adjusting your search or filters</p>
              </div>
            )}
          </div>

          {/* Report Preview */}
          <div className="lg:col-span-1">
            {selectedReportData ? (
              <Card className="sticky top-20">
                <CardHeader>
                  <CardTitle className="text-lg">Report Preview</CardTitle>
                </CardHeader>
                <CardContent className="space-y-4">
                  <div className="text-center py-6">
                    {(() => {
                      const Icon = reportTypeIcons[selectedReportData.type as keyof typeof reportTypeIcons] || FileText
                      const colors = reportTypeColors[selectedReportData.type as keyof typeof reportTypeColors]
                      return (
                        <div className={cn(
                          "mx-auto flex h-16 w-16 items-center justify-center rounded-xl",
                          colors
                        )}>
                          <Icon className="h-8 w-8" />
                        </div>
                      )
                    })()}
                    <h3 className="mt-4 font-semibold">{selectedReportData.title}</h3>
                    <p className="text-sm text-muted-foreground">{selectedReportData.subtitle}</p>
                  </div>

                  {selectedReportData.score && (
                    <div className="flex items-center justify-between rounded-lg bg-muted p-4">
                      <span className="text-sm font-medium">Score</span>
                      <span className={cn(
                        "text-2xl font-bold",
                        getScoreColor(selectedReportData.score)
                      )}>
                        {selectedReportData.score}%
                      </span>
                    </div>
                  )}

                  <div className="space-y-2 text-sm">
                    <div className="flex justify-between">
                      <span className="text-muted-foreground">Date</span>
                      <span>{selectedReportData.date}</span>
                    </div>
                    <div className="flex justify-between">
                      <span className="text-muted-foreground">Type</span>
                      <span className="capitalize">{selectedReportData.type}</span>
                    </div>
                  </div>

                  <div className="flex gap-2 pt-4">
                    <Button className="flex-1 gap-2" onClick={() => handleDownload(selectedReportData)}>
                      <Download className="h-4 w-4" />
                      Download
                    </Button>
                    <Button variant="outline" className="flex-1 gap-2">
                      <Eye className="h-4 w-4" />
                      View Full
                    </Button>
                  </div>
                  <div className="pt-1">
                    {deleteConfirmId === selectedReportData.id ? (
                      <div className="flex items-center gap-2">
                        <span className="text-xs text-muted-foreground flex-1">Delete permanently?</span>
                        <Button
                          size="sm" variant="destructive" className="h-7 px-2.5 text-xs"
                          onClick={() => handleDeleteReport(selectedReportData.id)}
                        >
                          Yes, Delete
                        </Button>
                        <Button
                          size="sm" variant="ghost" className="h-7 px-2 text-xs"
                          onClick={() => setDeleteConfirmId(null)}
                        >
                          Cancel
                        </Button>
                      </div>
                    ) : (
                      <Button
                        variant="ghost" size="sm"
                        className="w-full gap-2 text-muted-foreground hover:text-red-500 text-xs"
                        onClick={() => setDeleteConfirmId(selectedReportData.id)}
                      >
                        <Trash2 className="h-3.5 w-3.5" />
                        Delete Report
                      </Button>
                    )}
                  </div>
                </CardContent>
              </Card>
            ) : (
              <Card className="flex items-center justify-center min-h-[300px]">
                <div className="text-center text-muted-foreground">
                  <FileText className="mx-auto h-12 w-12 mb-4" />
                  <p>Select a report to preview</p>
                </div>
              </Card>
            )}
          </div>
        </motion.div>
      </motion.div>
    </AppShell>
  )
}
