"use client"

import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card"
import { Button } from "@/components/ui/button"
import { resumeAnalysis } from "@/lib/mock-data"
import { ProgressRing } from "@/components/dashboard/progress-ring"
import { 
  Download, 
  Upload, 
  CheckCircle, 
  AlertCircle, 
  XCircle,
  Briefcase,
  Tag,
  FileText,
  TrendingUp,
  ArrowRight,
  RotateCcw
} from "lucide-react"
import { cn } from "@/lib/utils"

interface ResumeAnalysisProps {
  fileName: string
  onReset: () => void
}

const statusConfig = {
  excellent: { icon: CheckCircle, color: "text-green-500", bg: "bg-green-500/10" },
  good: { icon: CheckCircle, color: "text-primary", bg: "bg-primary/10" },
  needs_improvement: { icon: AlertCircle, color: "text-yellow-500", bg: "bg-yellow-500/10" },
  poor: { icon: XCircle, color: "text-red-500", bg: "bg-red-500/10" },
}

export function ResumeAnalysis({ fileName, onReset }: ResumeAnalysisProps) {
  const analysis = resumeAnalysis

  const getScoreColor = (score: number) => {
    if (score >= 85) return "text-green-500"
    if (score >= 70) return "text-primary"
    if (score >= 50) return "text-yellow-500"
    return "text-red-500"
  }

  const handleDownloadReport = () => {
    const reportContent = `
INTERMATE RESUME ANALYSIS REPORT
================================

File: ${fileName}
Analysis Date: ${new Date().toLocaleDateString()}
ATS Score: ${analysis.atsScore}%

SECTION SCORES:
${Object.entries(analysis.sections).map(([section, data]) => 
  `- ${section.charAt(0).toUpperCase() + section.slice(1)}: ${data.score}% (${data.status.replace("_", " ")})`
).join("\n")}

MATCHED KEYWORDS:
${analysis.keywords.matched.join(", ")}

MISSING KEYWORDS:
${analysis.keywords.missing.join(", ")}

SUGGESTED KEYWORDS:
${analysis.keywords.suggested.join(", ")}

IMPROVEMENT SUGGESTIONS:
${analysis.suggestions.map((s, i) => `${i + 1}. [${s.priority.toUpperCase()}] ${s.section}: ${s.text}`).join("\n")}

JOB MATCHES:
${analysis.matchedJobs.map(j => `- ${j.title} at ${j.company}: ${j.match}% match`).join("\n")}

Generated by InterMate - AI-Powered Resume Analyzer
    `

    const blob = new Blob([reportContent], { type: "text/plain" })
    const url = URL.createObjectURL(blob)
    const a = document.createElement("a")
    a.href = url
    a.download = `InterMate_Resume_Report_${new Date().toISOString().split("T")[0]}.txt`
    document.body.appendChild(a)
    a.click()
    document.body.removeChild(a)
    URL.revokeObjectURL(url)
  }

  return (
    <div className="space-y-6">
      {/* ATS Score Overview */}
      <Card className="overflow-hidden">
        <div className="bg-gradient-to-r from-primary/10 via-primary/5 to-transparent p-6">
          <div className="flex flex-col items-center gap-6 md:flex-row md:justify-between">
            <div className="flex items-center gap-6">
              <ProgressRing progress={analysis.atsScore} size={120} strokeWidth={10}>
                <div className="text-center">
                  <span className={cn("text-3xl font-bold", getScoreColor(analysis.atsScore))}>
                    {analysis.atsScore}
                  </span>
                  <p className="text-xs text-muted-foreground">ATS Score</p>
                </div>
              </ProgressRing>
              <div>
                <h2 className="text-2xl font-bold">Resume Analyzed</h2>
                <p className="text-muted-foreground">{fileName}</p>
                <p className="text-sm text-muted-foreground mt-1">
                  Your resume has a good ATS compatibility score
                </p>
              </div>
            </div>
            <div className="flex gap-3">
              <Button variant="outline" onClick={onReset} className="gap-2">
                <RotateCcw className="h-4 w-4" />
                Analyze Another
              </Button>
              <Button onClick={handleDownloadReport} className="gap-2">
                <Download className="h-4 w-4" />
                Download Report
              </Button>
            </div>
          </div>
        </div>
      </Card>

      {/* Section Scores */}
      <Card>
        <CardHeader>
          <CardTitle className="flex items-center gap-2">
            <FileText className="h-5 w-5 text-primary" />
            Section Analysis
          </CardTitle>
        </CardHeader>
        <CardContent>
          <div className="grid gap-4 md:grid-cols-2 lg:grid-cols-3">
            {Object.entries(analysis.sections).map(([section, data]) => {
              const config = statusConfig[data.status as keyof typeof statusConfig]
              const Icon = config.icon
              return (
                <div
                  key={section}
                  className="flex items-center justify-between rounded-lg border border-border p-4"
                >
                  <div className="flex items-center gap-3">
                    <div className={cn("flex h-10 w-10 items-center justify-center rounded-lg", config.bg)}>
                      <Icon className={cn("h-5 w-5", config.color)} />
                    </div>
                    <div>
                      <p className="font-medium capitalize">{section}</p>
                      <p className="text-sm text-muted-foreground capitalize">
                        {data.status.replace("_", " ")}
                      </p>
                    </div>
                  </div>
                  <span className={cn("text-xl font-bold", getScoreColor(data.score))}>
                    {data.score}%
                  </span>
                </div>
              )
            })}
          </div>
        </CardContent>
      </Card>

      {/* Keywords */}
      <div className="grid gap-6 md:grid-cols-2">
        <Card>
          <CardHeader>
            <CardTitle className="flex items-center gap-2">
              <Tag className="h-5 w-5 text-green-500" />
              Matched Keywords ({analysis.keywords.matched.length})
            </CardTitle>
          </CardHeader>
          <CardContent>
            <div className="flex flex-wrap gap-2">
              {analysis.keywords.matched.map((keyword) => (
                <span
                  key={keyword}
                  className="rounded-full bg-green-500/10 px-3 py-1 text-sm font-medium text-green-500"
                >
                  {keyword}
                </span>
              ))}
            </div>
          </CardContent>
        </Card>

        <Card>
          <CardHeader>
            <CardTitle className="flex items-center gap-2">
              <Tag className="h-5 w-5 text-red-500" />
              Missing Keywords ({analysis.keywords.missing.length})
            </CardTitle>
          </CardHeader>
          <CardContent>
            <div className="flex flex-wrap gap-2">
              {analysis.keywords.missing.map((keyword) => (
                <span
                  key={keyword}
                  className="rounded-full bg-red-500/10 px-3 py-1 text-sm font-medium text-red-500"
                >
                  {keyword}
                </span>
              ))}
            </div>
            <p className="mt-3 text-sm text-muted-foreground">
              Consider adding these keywords to improve your match rate
            </p>
          </CardContent>
        </Card>
      </div>

      {/* Suggestions */}
      <Card>
        <CardHeader>
          <CardTitle className="flex items-center gap-2">
            <TrendingUp className="h-5 w-5 text-primary" />
            Improvement Suggestions
          </CardTitle>
        </CardHeader>
        <CardContent className="space-y-4">
          {analysis.suggestions.map((suggestion, index) => (
            <div
              key={index}
              className="flex items-start gap-4 rounded-lg border border-border p-4"
            >
              <span className={cn(
                "shrink-0 rounded-full px-2 py-0.5 text-xs font-medium uppercase",
                suggestion.priority === "high" && "bg-red-500/10 text-red-500",
                suggestion.priority === "medium" && "bg-yellow-500/10 text-yellow-500",
                suggestion.priority === "low" && "bg-green-500/10 text-green-500"
              )}>
                {suggestion.priority}
              </span>
              <div>
                <p className="font-medium">{suggestion.section}</p>
                <p className="text-sm text-muted-foreground">{suggestion.text}</p>
              </div>
            </div>
          ))}
        </CardContent>
      </Card>

      {/* Job Matches */}
      <Card>
        <CardHeader>
          <CardTitle className="flex items-center gap-2">
            <Briefcase className="h-5 w-5 text-primary" />
            Matching Job Roles
          </CardTitle>
        </CardHeader>
        <CardContent>
          <div className="space-y-3">
            {analysis.matchedJobs.map((job, index) => (
              <div
                key={index}
                className="flex items-center justify-between rounded-lg border border-border p-4 hover:border-primary/50 transition-colors cursor-pointer"
              >
                <div>
                  <p className="font-medium">{job.title}</p>
                  <p className="text-sm text-muted-foreground">{job.company}</p>
                </div>
                <div className="flex items-center gap-3">
                  <div className="text-right">
                    <p className={cn("text-lg font-bold", getScoreColor(job.match))}>
                      {job.match}%
                    </p>
                    <p className="text-xs text-muted-foreground">match</p>
                  </div>
                  <ArrowRight className="h-4 w-4 text-muted-foreground" />
                </div>
              </div>
            ))}
          </div>
        </CardContent>
      </Card>
    </div>
  )
}
