// InterMate Mock Data for FYP Platform

export const currentUser = {
  id: "user_001",
  name: "Aqsa Shafique",
  email: "aqsa.shafique@student.iba.edu.pk",
  avatar: "/avatars/aqsa.jpg",
  role: "Software Engineering Student",
  level: 12,
  xp: 2840,
  xpToNextLevel: 3000,
  streak: 7,
  joinedAt: "2024-09-15",
  completedInterviews: 23,
  resumeScore: 78,
  badges: ["Early Adopter", "Interview Pro", "Quick Learner", "7-Day Streak"],
}

export const userStats = {
  totalInterviews: 23,
  averageScore: 76,
  practiceHours: 45.5,
  resumeUploads: 3,
  peerReviews: 8,
  badgesEarned: 12,
  weeklyProgress: [
    { day: "Mon", interviews: 2, practice: 1.5 },
    { day: "Tue", interviews: 1, practice: 2 },
    { day: "Wed", interviews: 3, practice: 1 },
    { day: "Thu", interviews: 0, practice: 2.5 },
    { day: "Fri", interviews: 2, practice: 1.5 },
    { day: "Sat", interviews: 1, practice: 3 },
    { day: "Sun", interviews: 0, practice: 1 },
  ],
  skillProgress: [
    { skill: "Communication", score: 82, trend: "up" },
    { skill: "Technical Knowledge", score: 71, trend: "up" },
    { skill: "Problem Solving", score: 68, trend: "stable" },
    { skill: "Confidence", score: 75, trend: "up" },
    { skill: "Body Language", score: 79, trend: "down" },
  ],
}

export const recentActivity = [
  {
    id: "act_001",
    type: "interview",
    title: "Completed Technical Interview",
    description: "React & Node.js - Software Engineer role",
    score: 82,
    timestamp: "2025-04-11T10:30:00Z",
    icon: "video",
  },
  {
    id: "act_002",
    type: "resume",
    title: "Resume Analyzed",
    description: "ATS Score: 78% - 5 improvements suggested",
    score: 78,
    timestamp: "2025-04-10T15:45:00Z",
    icon: "file",
  },
  {
    id: "act_003",
    type: "learning",
    title: "Completed Module",
    description: "System Design Fundamentals - Level 3",
    score: null,
    timestamp: "2025-04-10T09:20:00Z",
    icon: "book",
  },
  {
    id: "act_004",
    type: "badge",
    title: "Badge Earned",
    description: "7-Day Streak Champion",
    score: null,
    timestamp: "2025-04-09T23:59:00Z",
    icon: "trophy",
  },
  {
    id: "act_005",
    type: "peer",
    title: "Peer Feedback Received",
    description: "From Aisha Khan on your behavioral interview",
    score: null,
    timestamp: "2025-04-09T14:30:00Z",
    icon: "users",
  },
]

export const badges = [
  { id: "b1", name: "Early Adopter", description: "Joined InterMate in the first month", icon: "rocket", earned: true, earnedAt: "2024-09-15" },
  { id: "b2", name: "First Interview", description: "Completed your first mock interview", icon: "play", earned: true, earnedAt: "2024-09-16" },
  { id: "b3", name: "Quick Learner", description: "Complete 5 learning modules in a week", icon: "zap", earned: true, earnedAt: "2024-09-22" },
  { id: "b4", name: "Interview Pro", description: "Score above 80 in 5 interviews", icon: "award", earned: true, earnedAt: "2024-10-05" },
  { id: "b5", name: "7-Day Streak", description: "Practice for 7 consecutive days", icon: "flame", earned: true, earnedAt: "2025-04-09" },
  { id: "b6", name: "Resume Master", description: "Achieve 90+ ATS score", icon: "file-check", earned: false, progress: 78 },
  { id: "b7", name: "Peer Helper", description: "Give feedback to 10 peers", icon: "heart", earned: false, progress: 80 },
  { id: "b8", name: "Perfectionist", description: "Score 100% in any interview", icon: "star", earned: false, progress: 82 },
  { id: "b9", name: "30-Day Streak", description: "Practice for 30 consecutive days", icon: "crown", earned: false, progress: 23 },
  { id: "b10", name: "Knowledge Master", description: "Complete all learning modules", icon: "graduation-cap", earned: false, progress: 45 },
]

export const interviewCategories = [
  { id: "tech", name: "Technical Interview", icon: "code", description: "DSA, System Design, Coding", count: 45 },
  { id: "behavioral", name: "Behavioral Interview", icon: "users", description: "STAR Method, Soft Skills", count: 32 },
  { id: "hr", name: "HR Interview", icon: "briefcase", description: "Company Fit, Career Goals", count: 28 },
  { id: "case", name: "Case Study", icon: "lightbulb", description: "Problem Solving, Analysis", count: 15 },
]

export const interviewQuestions = {
  tech: [
    { id: "q1", question: "Explain the difference between REST and GraphQL APIs.", difficulty: "medium", timeLimit: 180 },
    { id: "q2", question: "How would you design a URL shortening service like bit.ly?", difficulty: "hard", timeLimit: 300 },
    { id: "q3", question: "What is the time complexity of binary search and why?", difficulty: "easy", timeLimit: 120 },
    { id: "q4", question: "Explain the concept of closures in JavaScript.", difficulty: "medium", timeLimit: 180 },
    { id: "q5", question: "How does React's virtual DOM work?", difficulty: "medium", timeLimit: 180 },
  ],
  behavioral: [
    { id: "q6", question: "Tell me about a time you had to deal with a difficult team member.", difficulty: "medium", timeLimit: 180 },
    { id: "q7", question: "Describe a situation where you had to learn something quickly.", difficulty: "easy", timeLimit: 150 },
    { id: "q8", question: "How do you handle tight deadlines and pressure?", difficulty: "medium", timeLimit: 180 },
  ],
  hr: [
    { id: "q9", question: "Why do you want to work at our company?", difficulty: "easy", timeLimit: 120 },
    { id: "q10", question: "Where do you see yourself in 5 years?", difficulty: "easy", timeLimit: 120 },
    { id: "q11", question: "What are your salary expectations?", difficulty: "medium", timeLimit: 120 },
  ],
  case: [
    { id: "q12", question: "How would you increase revenue for a struggling coffee shop?", difficulty: "hard", timeLimit: 300 },
    { id: "q13", question: "Estimate the number of smartphones sold in Pakistan annually.", difficulty: "medium", timeLimit: 240 },
  ],
}

export const interviewHistory = [
  {
    id: "int_001",
    category: "Technical Interview",
    role: "Software Engineer",
    company: "Tech Corp",
    date: "2025-04-11",
    duration: 25,
    score: 82,
    strengths: ["Clear communication", "Good problem breakdown", "Strong React knowledge"],
    improvements: ["Consider edge cases", "Improve time management", "Practice system design"],
    questions: 5,
    status: "completed",
  },
  {
    id: "int_002",
    category: "Behavioral Interview",
    role: "Product Manager",
    company: "StartupXYZ",
    date: "2025-04-09",
    duration: 20,
    score: 75,
    strengths: ["Great storytelling", "Confident delivery", "Good examples"],
    improvements: ["Use STAR format consistently", "Be more concise", "Quantify achievements"],
    questions: 4,
    status: "completed",
  },
  {
    id: "int_003",
    category: "HR Interview",
    role: "Frontend Developer",
    company: "Digital Agency",
    date: "2025-04-07",
    duration: 15,
    score: 88,
    strengths: ["Authentic responses", "Good research on company", "Positive attitude"],
    improvements: ["Prepare more questions for interviewer"],
    questions: 6,
    status: "completed",
  },
  {
    id: "int_004",
    category: "Technical Interview",
    role: "Full Stack Developer",
    company: "Fintech Inc",
    date: "2025-04-05",
    duration: 30,
    score: 71,
    strengths: ["Solid fundamentals", "Good debugging approach"],
    improvements: ["Study advanced algorithms", "Practice whiteboard coding", "Review database concepts"],
    questions: 6,
    status: "completed",
  },
]

export const resumeAnalysis = {
  fileName: "Aqsa_Shafique_Resume.pdf",
  uploadedAt: "2025-04-10T15:45:00Z",
  atsScore: 78,
  sections: {
    contact: { score: 100, status: "excellent" },
    summary: { score: 75, status: "good" },
    experience: { score: 80, status: "good" },
    education: { score: 90, status: "excellent" },
    skills: { score: 65, status: "needs_improvement" },
    formatting: { score: 85, status: "good" },
  },
  keywords: {
    matched: ["React", "JavaScript", "Node.js", "MongoDB", "Git", "Agile", "REST API"],
    missing: ["TypeScript", "AWS", "Docker", "CI/CD", "GraphQL", "Testing"],
    suggested: ["Kubernetes", "Redis", "PostgreSQL", "Jest"],
  },
  suggestions: [
    { priority: "high", section: "Skills", text: "Add TypeScript to your skills - it's mentioned in 85% of similar job postings" },
    { priority: "high", section: "Experience", text: "Quantify your achievements with specific metrics (e.g., 'increased performance by 40%')" },
    { priority: "medium", section: "Summary", text: "Include your years of experience and top 3 technical skills in the summary" },
    { priority: "medium", section: "Skills", text: "Add cloud technologies (AWS/GCP/Azure) as they appear in most job descriptions" },
    { priority: "low", section: "Formatting", text: "Consider using a single-column layout for better ATS parsing" },
  ],
  matchedJobs: [
    { title: "Frontend Developer", company: "Tech Solutions", match: 82 },
    { title: "Full Stack Engineer", company: "StartupHub", match: 75 },
    { title: "React Developer", company: "Digital Labs", match: 88 },
  ],
}

export const learningModules = [
  {
    id: "lm_001",
    title: "Data Structures & Algorithms",
    description: "Master the fundamentals of DSA for technical interviews",
    category: "Technical",
    progress: 65,
    lessons: 24,
    completedLessons: 16,
    estimatedTime: "8 hours",
    difficulty: "intermediate",
    topics: ["Arrays", "Linked Lists", "Trees", "Graphs", "Dynamic Programming"],
  },
  {
    id: "lm_002",
    title: "System Design Fundamentals",
    description: "Learn to design scalable systems from scratch",
    category: "Technical",
    progress: 40,
    lessons: 18,
    completedLessons: 7,
    estimatedTime: "12 hours",
    difficulty: "advanced",
    topics: ["Scalability", "Load Balancing", "Caching", "Database Design", "Microservices"],
  },
  {
    id: "lm_003",
    title: "Behavioral Interview Mastery",
    description: "Perfect the STAR method and common behavioral questions",
    category: "Soft Skills",
    progress: 80,
    lessons: 12,
    completedLessons: 10,
    estimatedTime: "4 hours",
    difficulty: "beginner",
    topics: ["STAR Method", "Leadership Stories", "Conflict Resolution", "Teamwork Examples"],
  },
  {
    id: "lm_004",
    title: "Communication Skills",
    description: "Improve your verbal and non-verbal communication",
    category: "Soft Skills",
    progress: 55,
    lessons: 15,
    completedLessons: 8,
    estimatedTime: "5 hours",
    difficulty: "beginner",
    topics: ["Body Language", "Voice Modulation", "Active Listening", "Clarity"],
  },
  {
    id: "lm_005",
    title: "JavaScript Deep Dive",
    description: "Advanced JavaScript concepts for interviews",
    category: "Technical",
    progress: 90,
    lessons: 20,
    completedLessons: 18,
    estimatedTime: "6 hours",
    difficulty: "intermediate",
    topics: ["Closures", "Promises", "Event Loop", "Prototypes", "ES6+"],
  },
]

export const learningRecommendations = [
  { moduleId: "lm_002", reason: "Based on your last interview feedback on system design", priority: "high" },
  { moduleId: "lm_001", reason: "Complete remaining DSA topics to boost technical scores", priority: "medium" },
  { moduleId: "lm_004", reason: "Improve communication based on peer feedback", priority: "medium" },
]

export const peerReviews = [
  {
    id: "pr_001",
    interviewId: "int_002",
    interviewTitle: "Behavioral Interview - Product Manager",
    requestedBy: currentUser,
    reviewer: { id: "user_002", name: "Aisha Khan", avatar: "/avatars/aisha.jpg" },
    status: "completed",
    requestedAt: "2025-04-09T10:00:00Z",
    completedAt: "2025-04-09T14:30:00Z",
    overallRating: 4,
    comments: [
      { timestamp: 45, text: "Great opening! Very confident introduction.", type: "positive" },
      { timestamp: 120, text: "Try to be more specific about the outcome here.", type: "suggestion" },
      { timestamp: 210, text: "Excellent use of the STAR method in this response.", type: "positive" },
      { timestamp: 350, text: "Consider quantifying the impact of your actions.", type: "suggestion" },
    ],
    summary: "Overall strong performance with confident delivery. Work on adding more quantifiable results to your stories.",
  },
  {
    id: "pr_002",
    interviewId: "int_001",
    interviewTitle: "Technical Interview - Software Engineer",
    requestedBy: currentUser,
    reviewer: { id: "user_003", name: "Paman Shaikh", avatar: "/avatars/paman.jpg" },
    status: "pending",
    requestedAt: "2025-04-11T11:00:00Z",
  },
  {
    id: "pr_003",
    interviewId: "int_003",
    interviewTitle: "HR Interview - Frontend Developer",
    requestedBy: { id: "user_002", name: "Aisha Khan", avatar: "/avatars/aisha.jpg" },
    reviewer: currentUser,
    status: "action_required",
    requestedAt: "2025-04-08T09:00:00Z",
  },
]

export const chatMessages = [
  {
    id: "msg_001",
    reviewId: "pr_001",
    sender: { id: "user_002", name: "Aisha Khan" },
    message: "Hey! I've reviewed your interview recording. Overall great job!",
    timestamp: "2025-04-09T14:25:00Z",
  },
  {
    id: "msg_002",
    reviewId: "pr_001",
    sender: currentUser,
    message: "Thanks Aisha! I really appreciate the detailed feedback.",
    timestamp: "2025-04-09T14:32:00Z",
  },
  {
    id: "msg_003",
    reviewId: "pr_001",
    sender: { id: "user_002", name: "Aisha Khan" },
    message: "No problem! For the quantifying part, try to include numbers like percentages or dollar amounts.",
    timestamp: "2025-04-09T14:35:00Z",
  },
]

export const reports = [
  {
    id: "rep_001",
    type: "interview",
    title: "Technical Interview Report",
    subtitle: "Software Engineer - Tech Corp",
    date: "2025-04-11",
    score: 82,
    downloadUrl: "/reports/int_001.pdf",
  },
  {
    id: "rep_002",
    type: "resume",
    title: "Resume Analysis Report",
    subtitle: "ATS Score: 78%",
    date: "2025-04-10",
    score: 78,
    downloadUrl: "/reports/resume_001.pdf",
  },
  {
    id: "rep_003",
    type: "interview",
    title: "Behavioral Interview Report",
    subtitle: "Product Manager - StartupXYZ",
    date: "2025-04-09",
    score: 75,
    downloadUrl: "/reports/int_002.pdf",
  },
  {
    id: "rep_004",
    type: "weekly",
    title: "Weekly Progress Report",
    subtitle: "Week of April 7-13, 2025",
    date: "2025-04-13",
    score: null,
    downloadUrl: "/reports/weekly_015.pdf",
  },
  {
    id: "rep_005",
    type: "interview",
    title: "HR Interview Report",
    subtitle: "Frontend Developer - Digital Agency",
    date: "2025-04-07",
    score: 88,
    downloadUrl: "/reports/int_003.pdf",
  },
]

export const notifications = [
  { id: "n1", type: "peer", title: "New review request", message: "Aisha Khan requested your review", time: "2 hours ago", read: false },
  { id: "n2", type: "badge", title: "Badge earned!", message: "You earned the 7-Day Streak badge", time: "1 day ago", read: false },
  { id: "n3", type: "learning", title: "New module available", message: "Advanced React Patterns is now available", time: "2 days ago", read: true },
  { id: "n4", type: "interview", title: "Interview reminder", message: "You have a scheduled mock interview tomorrow", time: "3 days ago", read: true },
]
